# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2


class ApiStub(object):
    """The Api service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_time = channel.unary_unary(
                '/Api/get_time',
                request_serializer=api__pb2.TimeRequest.SerializeToString,
                response_deserializer=api__pb2.TimeResponse.FromString,
                )
        self.get_rural_population_percentage = channel.unary_unary(
                '/Api/get_rural_population_percentage',
                request_serializer=api__pb2.RuralRequest.SerializeToString,
                response_deserializer=api__pb2.RuralResponse.FromString,
                )


class ApiServicer(object):
    """The Api service definition.
    """

    def get_time(self, request, context):
        """Get time
        rpc ...
        $CODE_BEGIN
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_rural_population_percentage(self, request, context):
        """Get rural population percentage
        rpc ...
        $CODE_BEGIN
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_time': grpc.unary_unary_rpc_method_handler(
                    servicer.get_time,
                    request_deserializer=api__pb2.TimeRequest.FromString,
                    response_serializer=api__pb2.TimeResponse.SerializeToString,
            ),
            'get_rural_population_percentage': grpc.unary_unary_rpc_method_handler(
                    servicer.get_rural_population_percentage,
                    request_deserializer=api__pb2.RuralRequest.FromString,
                    response_serializer=api__pb2.RuralResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Api', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Api(object):
    """The Api service definition.
    """

    @staticmethod
    def get_time(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Api/get_time',
            api__pb2.TimeRequest.SerializeToString,
            api__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_rural_population_percentage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Api/get_rural_population_percentage',
            api__pb2.RuralRequest.SerializeToString,
            api__pb2.RuralResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
