# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\"\x15\n\x05Image\x12\x0c\n\x04path\x18\x01 \x01(\t\")\n\x05\x46\x61\x63\x65s\x12 \n\x0b\x63oordinates\x18\x01 \x03(\x0b\x32\x0b.Coordinate\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x32#\n\x03\x41pi\x12\x1c\n\x08MapFaces\x12\x06.Image\x1a\x06.Faces\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=12
  _IMAGE._serialized_end=33
  _FACES._serialized_start=35
  _FACES._serialized_end=76
  _COORDINATE._serialized_start=78
  _COORDINATE._serialized_end=112
  _API._serialized_start=114
  _API._serialized_end=149
# @@protoc_insertion_point(module_scope)
