# BUILDER IMAGE
FROM golang:alpine AS builder
WORKDIR /build 
ADD . /build/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .

# BEGINNING ON FINAL DOCKER IMAGE
# Talk about scratch at the end
FROM scratch
COPY --from=builder /build/main /app/
WORKDIR /app
CMD ["./main"]
