# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\"\r\n\x0bTimeRequest\"/\n\x0cTimeResponse\x12\t\n\x01h\x18\x01 \x01(\x03\x12\t\n\x01m\x18\x02 \x01(\x03\x12\t\n\x01s\x18\x03 \x01(\x03\"3\n\x12\x43ountryYearRequest\x12\x0c\n\x04year\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\"$\n\x13\x43ountryYearResponse\x12\r\n\x05value\x18\x01 \x01(\x01\x32\x37\n\x0bTimeService\x12(\n\x07GetTime\x12\x0c.TimeRequest\x1a\r.TimeResponse\"\x00\x32S\n\x12\x43ountryYearService\x12=\n\x0eGetCountryYear\x12\x13.CountryYearRequest\x1a\x14.CountryYearResponse\"\x00\x62\x06proto3')



_TIMEREQUEST = DESCRIPTOR.message_types_by_name['TimeRequest']
_TIMERESPONSE = DESCRIPTOR.message_types_by_name['TimeResponse']
_COUNTRYYEARREQUEST = DESCRIPTOR.message_types_by_name['CountryYearRequest']
_COUNTRYYEARRESPONSE = DESCRIPTOR.message_types_by_name['CountryYearResponse']
TimeRequest = _reflection.GeneratedProtocolMessageType('TimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIMEREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:TimeRequest)
  })
_sym_db.RegisterMessage(TimeRequest)

TimeResponse = _reflection.GeneratedProtocolMessageType('TimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIMERESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:TimeResponse)
  })
_sym_db.RegisterMessage(TimeResponse)

CountryYearRequest = _reflection.GeneratedProtocolMessageType('CountryYearRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYYEARREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:CountryYearRequest)
  })
_sym_db.RegisterMessage(CountryYearRequest)

CountryYearResponse = _reflection.GeneratedProtocolMessageType('CountryYearResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYYEARRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:CountryYearResponse)
  })
_sym_db.RegisterMessage(CountryYearResponse)

_TIMESERVICE = DESCRIPTOR.services_by_name['TimeService']
_COUNTRYYEARSERVICE = DESCRIPTOR.services_by_name['CountryYearService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEREQUEST._serialized_start=13
  _TIMEREQUEST._serialized_end=26
  _TIMERESPONSE._serialized_start=28
  _TIMERESPONSE._serialized_end=75
  _COUNTRYYEARREQUEST._serialized_start=77
  _COUNTRYYEARREQUEST._serialized_end=128
  _COUNTRYYEARRESPONSE._serialized_start=130
  _COUNTRYYEARRESPONSE._serialized_end=166
  _TIMESERVICE._serialized_start=168
  _TIMESERVICE._serialized_end=223
  _COUNTRYYEARSERVICE._serialized_start=225
  _COUNTRYYEARSERVICE._serialized_end=308
# @@protoc_insertion_point(module_scope)
