lewgon_dbt:
  outputs:
    dev:
      dataset: dbt_hvandernotte
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/lewagon_dbt/le-wagon-de-bootcamp.json
      location: US
      method: service-account
      priority: interactive
      project: wagon-bootcamp-280715
      threads: 1
      type: bigquery
  target: dev
