
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_lewagon'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_nicolas'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# https://docs.getdbt.com/reference/project-configs/query-comment#compilation-context
# Adds some comment at the top of each compiled model
# To give information about some key variables (target etc)
query-comment:
  comment: "High level info about the query setup"
  append: false
  job-label: false  # BigQuery only

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_lewagon:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view

vars:
  # Even for prod, let's make it recent
  # 2018-01-01 was processing, for dbt_nbancel.stg_hackernews_full, 11.9GB and 15.7m rows
  start_date_dataset: "'2022-06-01'"
