FROM ubuntu:20.04

#Do not use env as this would persist after the build and would impact your containers, children images
ARG DEBIAN_FRONTEND=noninteractive

# force the stdout and stderr streams to be unbuffered. 
ENV PYTHONUNBUFFERED 1 

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get -y install python3.8 python3-pip
RUN pip3 install fastapi==0.78.0 SQLAlchemy==1.4.36 alembic==1.7.7 uvicorn[standard]==0.17.6
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /server

COPY ./  ./

EXPOSE 8000

ENTRYPOINT [ "uvicorn" ]

CMD ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]

#size: 493MB