[tool.poetry]
name = "lecture-demo"
version = "0.1.0"
description = ""
authors = ["Oliver Giles <oliver.giles@lewagon.org>"]
readme = "README.md"
packages = [{include = "lecture_demo"}]

[tool.poetry.dependencies]
python = "^3.8"
google-cloud-pubsub = "^2.18.4"
apache-beam = "^2.51.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
