.PHONY: install


install:
	curl --output ./database/init/postgres-movies-no-owner-w01d04.sql.gz https://storage.googleapis.com/lewagon-data-engineering-bootcamp-assets/datasets/movies/w1d3/postgres-movies-no-owner-w01d04.sql.gz
