FROM python:3.8.14-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update \
  && apt-get -y install software-properties-common \
  && add-apt-repository ppa:deadsnakes/ppa \
  && pip install --no-cache-dir poetry \
  && rm -rf /var/lib/apt/lists/* \
  && useradd -uid 10000 -ms /bin/bash runner

WORKDIR /home/runner/app

COPY . /app/

RUN poetry install --only main

USER 10000

ENV PATH="${PATH}:/home/runner.local/bin"

EXPOSE 8000

ENTRYPOINT [ "poetry", "run" ]

CMD uvicorn app.main:app --host 0.0.0.0 --port 8000
