FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED 1

RUN apt-get -y update
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get -y update
RUN apt-get install -y python3.8
RUN apt-get install -y python3-pip

RUN pip install fastapi==0.78.0
RUN pip install SQLAlchemy==1.4.36
RUN pip install Alembic==1.7.7
RUN pip install uvicorn==0.17.6

WORKDIR /app

COPY . /app/

EXPOSE 8000

ENTRYPOINT [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
