# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cserver.proto\x12\x08hnstream"2\n\x0eGetNextRequest\x12\x11\n\tunix_time\x18\x01 \x01(\x03\x12\r\n\x05limit\x18\x02 \x01(\x03"v\n\x05Story\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05score\x18\x02 \x01(\x03\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\n\n\x02\x62y\x18\x04 \x01(\t\x12\r\n\x05title\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x0c\n\x04text\x18\x07 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x08 \x01(\t"n\n\x07\x43omment\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04time\x18\x02 \x01(\x03\x12\x0e\n\x06parent\x18\x03 \x01(\x03\x12\x0f\n\x07ranking\x18\x04 \x01(\x03\x12\n\n\x02\x62y\x18\x05 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t\x12\x0c\n\x04text\x18\x07 \x01(\t":\n\x16GetNextStoriesResponse\x12 \n\x07stories\x18\x01 \x03(\x0b\x32\x0f.hnstream.Story">\n\x17GetNextCommentsResponse\x12#\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x11.hnstream.Comment2\xae\x01\n\nHnstreamer\x12P\n\x0fGetNextComments\x12\x18.hnstream.GetNextRequest\x1a!.hnstream.GetNextCommentsResponse"\x00\x12N\n\x0eGetNextStories\x12\x18.hnstream.GetNextRequest\x1a .hnstream.GetNextStoriesResponse"\x00\x62\x06proto3'
)


_GETNEXTREQUEST = DESCRIPTOR.message_types_by_name["GetNextRequest"]
_STORY = DESCRIPTOR.message_types_by_name["Story"]
_COMMENT = DESCRIPTOR.message_types_by_name["Comment"]
_GETNEXTSTORIESRESPONSE = DESCRIPTOR.message_types_by_name["GetNextStoriesResponse"]
_GETNEXTCOMMENTSRESPONSE = DESCRIPTOR.message_types_by_name["GetNextCommentsResponse"]
GetNextRequest = _reflection.GeneratedProtocolMessageType(
    "GetNextRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETNEXTREQUEST,
        "__module__": "server_pb2"
        # @@protoc_insertion_point(class_scope:hnstream.GetNextRequest)
    },
)
_sym_db.RegisterMessage(GetNextRequest)

Story = _reflection.GeneratedProtocolMessageType(
    "Story",
    (_message.Message,),
    {
        "DESCRIPTOR": _STORY,
        "__module__": "server_pb2"
        # @@protoc_insertion_point(class_scope:hnstream.Story)
    },
)
_sym_db.RegisterMessage(Story)

Comment = _reflection.GeneratedProtocolMessageType(
    "Comment",
    (_message.Message,),
    {
        "DESCRIPTOR": _COMMENT,
        "__module__": "server_pb2"
        # @@protoc_insertion_point(class_scope:hnstream.Comment)
    },
)
_sym_db.RegisterMessage(Comment)

GetNextStoriesResponse = _reflection.GeneratedProtocolMessageType(
    "GetNextStoriesResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETNEXTSTORIESRESPONSE,
        "__module__": "server_pb2"
        # @@protoc_insertion_point(class_scope:hnstream.GetNextStoriesResponse)
    },
)
_sym_db.RegisterMessage(GetNextStoriesResponse)

GetNextCommentsResponse = _reflection.GeneratedProtocolMessageType(
    "GetNextCommentsResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETNEXTCOMMENTSRESPONSE,
        "__module__": "server_pb2"
        # @@protoc_insertion_point(class_scope:hnstream.GetNextCommentsResponse)
    },
)
_sym_db.RegisterMessage(GetNextCommentsResponse)

_HNSTREAMER = DESCRIPTOR.services_by_name["Hnstreamer"]
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _GETNEXTREQUEST._serialized_start = 26
    _GETNEXTREQUEST._serialized_end = 76
    _STORY._serialized_start = 78
    _STORY._serialized_end = 196
    _COMMENT._serialized_start = 198
    _COMMENT._serialized_end = 308
    _GETNEXTSTORIESRESPONSE._serialized_start = 310
    _GETNEXTSTORIESRESPONSE._serialized_end = 368
    _GETNEXTCOMMENTSRESPONSE._serialized_start = 370
    _GETNEXTCOMMENTSRESPONSE._serialized_end = 432
    _HNSTREAMER._serialized_start = 435
    _HNSTREAMER._serialized_end = 609
# @@protoc_insertion_point(module_scope)
