version: '3'

services:
  frontend:
    image: europe-west1-docker.pkg.dev/data-engineering-students/student-images/style-frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - style-storage:/storage
  backend:
    image: europe-west1-docker.pkg.dev/data-engineering-students/student-images/style-backend
    volumes:
      - style-storage:/storage
    ports:
      - 8080

volumes:
  style-storage:
