version: '3'
services:
    postgres:
        image: postgres:14
        healthcheck:
            test: ["CMD", "pg_isready -d db -U airflow"]
            interval: 5s
            retries: 5
        restart: always
        

    webserver:
        build: .
        command: poetry run scripts/entrypoint.sh
        depends_on:
            - postgres
            - scheduler
        restart: on-failure
        healthcheck:
            test: ["CMD", "-f", "/home/airflow/airflow-webserver.pid"]
            interval: 30s
            timeout: 30s
            retries: 3
        # $DEL_BEGIN
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
            - POSTGRES_DB=db
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=airflow
        volumes:
            - ./dags:/app/airflow/dags
            - ./data:/app/airflow/data
            - ./logs:/app/airflow/logs
        ports:
            - 8080:8080
        # $DEL_BEGIN
