version: '3'
services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=db
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=airflow
        volumes:
            - ./database/:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready -d db -U airflow"]
            interval: 5s
            retries: 5
        ports:
          - "5432:5432"
        restart: always

    scheduler:
        build: .
        command: poetry run scripts/scheduler_entrypoint.sh
        restart: on-failure
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
            - PROJECT_ID=$PROJECT_ID
            - PRIVATE_KEY_ID=$PRIVATE_KEY_ID
            - PRIVATE_KEY=$PRIVATE_KEY
            - CLIENT_EMAIL=$CLIENT_EMAIL
            - CLIENT_ID=$CLIENT_ID
            - CLIENT_X509_CERT_URL=$CLIENT_X509_CERT_URL
        volumes:
            - ./dags:/opt/airflow/dags
            - ./data:/opt/airflow/data
            - ./logs:/opt/airflow/logs
            
    webserver:
        build: .
        command: poetry run scripts/webserver_entrypoint.sh
        restart: on-failure
        depends_on:
            - postgres
            - scheduler
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
            - POSTGRES_DB=db
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=airflow
        volumes:
            - ./dags:/opt/airflow/dags
            - ./data:/opt/airflow/data
            - ./lewagon_dbt:/opt/airflow/lewagon_dbt
            - ./logs:/opt/airflow/logs
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
