version: "3.8"

volumes:
  tweetapp:

services:
  tweet-service:
    container_name: tweet-service
    build:
      context: .
    ports:
      - "5001:5001"
    volumes:
      - tweetapp:/tweetapp
    restart: always
