version: '3'
services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    environment:
      - POSTGRES_DB=ikea
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=lewagon
    volumes:
      - ./data/database/:/var/lib/postgresql/data
      - ./data/:/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "ikea", "-U", "lewagon" ]
      interval: 5s
      retries: 5
    ports:
      - 5433:5432
    restart: always
