bigquery_schemas = {
    "SalesTerritory": [
        {"name": "TerritoryID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "Name", "type": "STRING", "mode": "REQUIRED"},
        {"name": "CountryRegionCode", "type": "STRING", "mode": "REQUIRED"},
        {"name": "Group", "type": "STRING", "mode": "REQUIRED"},
        {"name": "SalesYTD", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "SalesLastYear", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "CostYTD", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "CostLastYear", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "rowguid", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "SalesTerritoryHistory": [
        {"name": "BusinessEntityID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "TerritoryID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "StartDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "EndDate", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "rowguid", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "ShoppingCartItem": [
        {"name": "ShoppingCartItemID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ShoppingCartID", "type": "STRING", "mode": "REQUIRED"},
        {"name": "Quantity", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ProductID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "DateCreated", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "SpecialOffer": [
        {"name": "SpecialOfferID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "Description", "type": "STRING", "mode": "REQUIRED"},
        {"name": "DiscountPct", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "Type", "type": "STRING", "mode": "REQUIRED"},
        {"name": "Category", "type": "STRING", "mode": "REQUIRED"},
        {"name": "StartDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "EndDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "MinQty", "type": "INT64", "mode": "REQUIRED"},
        {"name": "MaxQty", "type": "INT64", "mode": "NULLABLE"},
        {"name": "rowguid", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "SpecialOfferProduct": [
        {"name": "SpecialOfferID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ProductID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "rowguid", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "Store": [
        {"name": "BusinessEntityID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "Name", "type": "STRING", "mode": "REQUIRED"},
        {"name": "SalesPersonID", "type": "INT64", "mode": "NULLABLE"},
        {"name": "rowguid", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
        pass  # YOUR CODE HERE
    ],
    "CountryRegionCurrency": [
        {"name": "CountryRegionCode", "type": "STRING", "mode": "REQUIRED"},
        {"name": "CurrencyCode", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "Currency": [
        {"name": "CurrencyCode", "type": "STRING", "mode": "REQUIRED"},
        {"name": "Name", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "CurrencyRate": [
        {"name": "CurrencyRateID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "CurrencyRateDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "FromCurrencyCode", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ToCurrencyCode", "type": "STRING", "mode": "REQUIRED"},
        {"name": "AverageRate", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "EndOfDayRate", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "Customer": [
        {"name": "CustomerID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "PersonID", "type": "INT64", "mode": "NULLABLE"},
        {"name": "StoreID", "type": "INT64", "mode": "NULLABLE"},
        {"name": "TerritoryID", "type": "INT64", "mode": "NULLABLE"},
        {"name": "AccountNumber", "type": "STRING", "mode": "NULLABLE"},
        {"name": "rowguid", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "PersonCreditCard": [
        {"name": "BusinessEntityID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "CreditCardID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "SalesOrderDetail": [
        {"name": "SalesOrderID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "SalesOrderDetailID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "CarrierTrackingNumber", "type": "STRING", "mode": "NULLABLE"},
        {"name": "OrderQty", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ProductID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "SpecialOfferID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "UnitPrice", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "UnitPriceDiscount", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "LineTotal", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "rowguid", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "SalesOrderHeader": [
        {"name": "SalesOrderID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "RevisionNumber", "type": "INT64", "mode": "REQUIRED"},
        {"name": "OrderDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "DueDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
        {"name": "ShipDate", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "Status", "type": "INT64", "mode": "REQUIRED"},
        {"name": "OnlineOrderFlag", "type": "BOOL", "mode": "REQUIRED"},
        {"name": "SalesOrderNumber", "type": "STRING", "mode": "NULLABLE"},
        {"name": "PurchaseOrderNumber", "type": "STRING", "mode": "NULLABLE"},
        {"name": "AccountNumber", "type": "STRING", "mode": "NULLABLE"},
        {"name": "CustomerID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "SalesPersonID", "type": "INT64", "mode": "NULLABLE"},
        {"name": "TerritoryID", "type": "INT64", "mode": "NULLABLE"},
        {"name": "BillToAddressID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ShipToAddressID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ShipMethodID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "CreditCardID", "type": "INT64", "mode": "NULLABLE"},
        {"name": "CreditCardApprovalCode", "type": "STRING", "mode": "NULLABLE"},
        {"name": "CurrencyRateID", "type": "INT64", "mode": "NULLABLE"},
        {"name": "SubTotal", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "TaxAmt", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "Freight", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "TotalDue", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "Comment", "type": "STRING", "mode": "NULLABLE"},
        {"name": "rowguid", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "SalesOrderHeaderSalesReason": [
        {"name": "SalesOrderID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "SalesReasonID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "CreditCard": [
        {"name": "CreditCardID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "CardType", "type": "STRING", "mode": "REQUIRED"},
        {"name": "CardNumber", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ExpMonth", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ExpYear", "type": "INT64", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
    "SalesTaxRate": [
        {"name": "SalesTaxRateID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "StateProvinceID", "type": "INT64", "mode": "REQUIRED"},
        {"name": "TaxType", "type": "INT64", "mode": "REQUIRED"},
        {"name": "TaxRate", "type": "FLOAT64", "mode": "REQUIRED"},
        {"name": "Name", "type": "STRING", "mode": "REQUIRED"},
        {"name": "rowguid", "type": "STRING", "mode": "REQUIRED"},
        {"name": "ModifiedDate", "type": "TIMESTAMP", "mode": "REQUIRED"},
    ],
}
if __name__ == "__main__":
    print((bigquery_schemas.keys()))
    print(len(bigquery_schemas.keys()))
