# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\"\x13\n\x11GetNumbersRequest\"#\n\x12GetNumbersResponse\x12\r\n\x05value\x18\x01 \x01(\x05\x32P\n\x13NumberStreamService\x12\x39\n\nGetNumbers\x12\x12.GetNumbersRequest\x1a\x13.GetNumbersResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETNUMBERSREQUEST._serialized_start=19
  _GETNUMBERSREQUEST._serialized_end=38
  _GETNUMBERSRESPONSE._serialized_start=40
  _GETNUMBERSRESPONSE._serialized_end=75
  _NUMBERSTREAMSERVICE._serialized_start=77
  _NUMBERSTREAMSERVICE._serialized_end=157
# @@protoc_insertion_point(module_scope)
