"""added all tables and seed

Revision ID: a74b5a5c331a
Revises:
Create Date: 2022-11-21 17:31:14.020544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a74b5a5c331a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    tweets = op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    likes = op.create_table(
        "likes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("tweet_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["tweets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # Manually Seed our 3 tables
    op.bulk_insert(
        users,
        [
            {"email": "oliver.giles@lewagon.org", "hashed_password": "notreally"},
            {"email": "bruno@lewagon.org", "hashed_password": "notreallyeither"},
        ],
    )
    op.bulk_insert(
        tweets,
        [
            {"text": "i love data eng", "owner_id": "1", "like_count": "2"},
            {"text": "i love postgres", "owner_id": "2", "like_count": "1"},
            {"text": "i love docker", "owner_id": "1", "like_count": "0"},
        ],
    )
    op.bulk_insert(
        likes,
        [
            {"owner_id": "1", "tweet_id": "1"},
            {"owner_id": "2", "tweet_id": "1"},
            {"owner_id": "1", "tweet_id": "2"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("likes")
    op.drop_table("tweets")
    op.drop_table("users")
    # ### end Alembic commands ###
