[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["S. Saunier <seb@lewagon.org>"]
packages = [{include = "api"}]

[tool.poetry.dependencies]
python = "3.8.14"
pandas = "^1.4.2"
pyarrow = "^8.0.0"
openpyxl = "^3.0.10"
jupyterlab = "^3.4.2"
fastapi = "^0.78.0"
grpcio-tools = "1.47.0"
lewagonde = { path = "../../../common/lewagonde/", develop = true }
uvicorn = {extras = ["standard"], version = "^0.17.6"}
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pytest = "7.1.2"
ipython = "^8.4.0"
black = "^22.3.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 160
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 160
multi_line_output = 3
include_trailing_comma = true

[virtualenvs]
in-project = true
