Table customer {
  customer_id int [pk, increment] // auto-increment
  first_name varchar
  last_name varchar
  email_address varchar
}

Table order {
  order_id int [pk] // primary key
  customer_id int [not null]
  total_price decimal
  status order_statuses
  created_at varchar [note: 'When order created'] // add column note
}

Table order_item {
  order_id int [ref: > order.order_id] // inline relationship (many-to-one)
  product_id int
  quantity int [default: 1] // default value
}

Table product {
  product_id int [pk]
  product_name varchar
  product_price decimal
}

Enum order_statuses {
  completed
  canceled
}

Ref: order.customer_id > customer.customer_id
Ref: order_item.product_id > product.product_id
