services:
  webapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: dockerfile-fastapi
    restart: on-failure
    ports:
      - 8000:8111
    networks:
      - backend
    volumes:
      - ./api:/app/app
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8111 --reload"
    environment:
      - POSTGRES_DATABASE_URL=postgresql+psycopg2://$APP_DB_USER:$APP_DB_PASS@db:5432/$APP_DB_NAME
    depends_on:
      - db
    

  db:
    image: postgres:14.2
    restart: on-failure
    ports:
      - 5433:5432
    environment:
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - APP_DB_USER=$APP_DB_USER
        - APP_DB_PASS=$APP_DB_PASS
        - APP_DB_NAME=$APP_DB_NAME
    networks:
      - backend
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready",  "-U",  "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    

networks:
  backend:
    driver: bridge
