[tool.poetry]
name = "mapreduce"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "lwmr"}]

[tool.poetry.dependencies]
python = "^3.8"
lewagonde = { path = "../../../common/lewagonde/", develop = true }


[tool.poetry.dev-dependencies]
ipython = "^8.8.0"
pytest = "^7.2.0"
ipdb = "^0.13.11"

[tool.poetry.group.dev.dependencies]
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
