version: "3.9"
services:
  database:
    image: postgres:14
    restart: always
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=f1db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5431:5431

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database

  streamlit:
    build:
      context: .
    restart: always
    volumes:
      - ./app:/app/app
      - ./.streamlit:/app/.streamlit/
    command: ["streamlit", "run", "app/main.py"]
    ports:
      - 8501:8501
    depends_on:
      - database
