version: "3.8"

volumes:
  userapp:

services:
  user-service:
    container_name: user-service
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - userapp:/userapp
    restart: always
