[tool.poetry]
name = "lwface"
version = "0.1.0"
description = ""
authors = ["S. Saunier <seb@lewagon.org>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
lewagonde = { path = "../../../common/lewagonde/", develop = true }
streamlit = "^1.10.0"
scikit-image = "^0.19.3"
torch = "^1.12.0"
streamlit-webrtc = "^0.42.0"
Pillow = "^9.2.0"
numpy = "^1.23.0"
av = "^9.2.0"
watchdog = "^2.1.9"
matplotlib = "^3.5.2"
opencv-python = "^4.6.0"
tqdm = "^4.64.0"
torchvision = "^0.13.0"
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]
pytest = "7.1.2"
ipython = "^8.4.0"
black = "^22.3.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 160
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 160
multi_line_output = 3
include_trailing_comma = true

[virtualenvs]
in-project = true
