version: '3'
services:
    git-sync:
      image: k8s.gcr.io/git-sync/git-sync:v3.6.5
      volumes:
        - gitdags:/tmp/git
      environment:
        - GIT_SYNC_REPO=https://github.com/ogiles1999/test-dag-repo.git
        - GIT_SYNC_SSH=false
        - GIT_SYNC_USERNAME=token
        - GIT_SYNC_PASSWORD=${GIT_SYNC_PASSWORD_ENV}
        - GIT_SYNC_WAIT=60
        - GIT_SYNC_BRANCH=main
        - GIT_SYNC_DEST=dags
        - GIT_SYNC_PERMISSIONS=0777


    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=db
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=airflow
        volumes:
            - ./database/:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready -d db -U airflow"]
            interval: 5s
            retries: 5
        ports:
          - "5433:5432"
        restart: always

    scheduler:
        build: .
        command: poetry run airflow scheduler
        restart: on-failure
        depends_on:
            - postgres
            - git-sync
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DEBUG__FAIL_FAST=true
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
            - AIRFLOW__CORE__DAGS_FOLDER=/app/airflow/dags/dags
            - AIRFLOW__CORE__MIN_FILE_PROCESS_INTERVAL=15
        volumes:
            - gitdags:/app/airflow/dags
            - ./data:/app/airflow/data
            - ./logs:/app/airflow/logs
        tty: true
        stdin_open: true

    webserver:
        build: .
        command: poetry run scripts/entrypoint.sh
        restart: on-failure
        depends_on:
            - postgres
            - scheduler
            - git-sync
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
            - AIRFLOW__CORE__DAGS_FOLDER=/app/airflow/dags/dags
            - AIRFLOW__CORE__MIN_FILE_PROCESS_INTERVAL=15
            - POSTGRES_DB=db
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=airflow
        volumes:
            - gitdags:/app/airflow/dags
            - ./data:/app/airflow/data
            - ./logs:/app/airflow/logs
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        tty: true
        stdin_open: true

volumes:
  gitdags:
