version: '3.9'
services:
  webapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: dockerfile-fastapi
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./app-no-database:/server/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]