# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\"\r\n\x0bTimeRequest\"/\n\x0cTimeResponse\x12\t\n\x01h\x18\x01 \x01(\x03\x12\t\n\x01m\x18\x02 \x01(\x03\x12\t\n\x01s\x18\x03 \x01(\x03\"-\n\x0cRuralRequest\x12\x0c\n\x04year\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\"\x1e\n\rRuralResponse\x12\r\n\x05value\x18\x01 \x01(\x01\x32p\n\x03\x41pi\x12(\n\x07GetTime\x12\x0c.TimeRequest\x1a\r.TimeResponse\"\x00\x12?\n\x1cGetRuralPopulationPercentage\x12\r.RuralRequest\x1a\x0e.RuralResponse\"\x00\x62\x06proto3')



_TIMEREQUEST = DESCRIPTOR.message_types_by_name['TimeRequest']
_TIMERESPONSE = DESCRIPTOR.message_types_by_name['TimeResponse']
_RURALREQUEST = DESCRIPTOR.message_types_by_name['RuralRequest']
_RURALRESPONSE = DESCRIPTOR.message_types_by_name['RuralResponse']
TimeRequest = _reflection.GeneratedProtocolMessageType('TimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIMEREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:TimeRequest)
  })
_sym_db.RegisterMessage(TimeRequest)

TimeResponse = _reflection.GeneratedProtocolMessageType('TimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIMERESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:TimeResponse)
  })
_sym_db.RegisterMessage(TimeResponse)

RuralRequest = _reflection.GeneratedProtocolMessageType('RuralRequest', (_message.Message,), {
  'DESCRIPTOR' : _RURALREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:RuralRequest)
  })
_sym_db.RegisterMessage(RuralRequest)

RuralResponse = _reflection.GeneratedProtocolMessageType('RuralResponse', (_message.Message,), {
  'DESCRIPTOR' : _RURALRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:RuralResponse)
  })
_sym_db.RegisterMessage(RuralResponse)

_API = DESCRIPTOR.services_by_name['Api']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEREQUEST._serialized_start=13
  _TIMEREQUEST._serialized_end=26
  _TIMERESPONSE._serialized_start=28
  _TIMERESPONSE._serialized_end=75
  _RURALREQUEST._serialized_start=77
  _RURALREQUEST._serialized_end=122
  _RURALRESPONSE._serialized_start=124
  _RURALRESPONSE._serialized_end=154
  _API._serialized_start=156
  _API._serialized_end=268
# @@protoc_insertion_point(module_scope)
