# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lwapi import api_pb2 as api__pb2


class ApiStub(object):
    """The Api service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTime = channel.unary_unary(
                '/Api/GetTime',
                request_serializer=api__pb2.TimeRequest.SerializeToString,
                response_deserializer=api__pb2.TimeResponse.FromString,
                )
        self.GetRuralPopulationPercentage = channel.unary_unary(
                '/Api/GetRuralPopulationPercentage',
                request_serializer=api__pb2.RuralRequest.SerializeToString,
                response_deserializer=api__pb2.RuralResponse.FromString,
                )


class ApiServicer(object):
    """The Api service definition.
    """

    def GetTime(self, request, context):
        """Get time
        rpc ...
        $CODE_BEGIN
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuralPopulationPercentage(self, request, context):
        """Get rural population percentage
        rpc ...
        $CODE_BEGIN
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=api__pb2.TimeRequest.FromString,
                    response_serializer=api__pb2.TimeResponse.SerializeToString,
            ),
            'GetRuralPopulationPercentage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuralPopulationPercentage,
                    request_deserializer=api__pb2.RuralRequest.FromString,
                    response_serializer=api__pb2.RuralResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Api', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Api(object):
    """The Api service definition.
    """

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Api/GetTime',
            api__pb2.TimeRequest.SerializeToString,
            api__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRuralPopulationPercentage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Api/GetRuralPopulationPercentage',
            api__pb2.RuralRequest.SerializeToString,
            api__pb2.RuralResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
