[tool.poetry]
name = "python-distribution"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
dask = "^2022.12.1"
pandas = "^1.5.2"
fastparquet = "^2022.12.0"
polars = "^0.15.8"
numpy = "^1.24.1"
jupyter = "^1.0.0"
notebook = "^6.5.2"
graphviz = "^0.20.1"
pydot = "^1.4.2"
s3fs = "^2022.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = ["optional: not required, nor saved in test_output.txt"]

[virtualenvs]
in-project = true
