worker:
  replicas: 3
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 3.5Gi
  env:
    - name: EXTRA_PIP_PACKAGES
      value: pyarrow==10.0.1 dask==2022.01.1

jupyter:
  enabled: false
