# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generated_proto.api_pb2 as api__pb2


class TimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTime = channel.unary_unary(
                '/TimeService/GetTime',
                request_serializer=api__pb2.TimeRequest.SerializeToString,
                response_deserializer=api__pb2.TimeResponse.FromString,
                )


class TimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=api__pb2.TimeRequest.FromString,
                    response_serializer=api__pb2.TimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TimeService/GetTime',
            api__pb2.TimeRequest.SerializeToString,
            api__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CountryYearServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCountryYear = channel.unary_unary(
                '/CountryYearService/GetCountryYear',
                request_serializer=api__pb2.CountryYearRequest.SerializeToString,
                response_deserializer=api__pb2.CountryYearResponse.FromString,
                )


class CountryYearServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCountryYear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountryYearServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCountryYear': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCountryYear,
                    request_deserializer=api__pb2.CountryYearRequest.FromString,
                    response_serializer=api__pb2.CountryYearResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CountryYearService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CountryYearService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCountryYear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CountryYearService/GetCountryYear',
            api__pb2.CountryYearRequest.SerializeToString,
            api__pb2.CountryYearResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
