name: Merge Challenge Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  merge_cha_pr:
    runs-on: ubuntu-latest
    steps:
      - id: merge-check
        name: Check if PR is closed via merge
        run: |
          if [[ ${{ github.event.pull_request.merged }} == true ]]
          then
            echo "[OK] PR merged"
            echo "PR_MERGED=true" >> $GITHUB_OUTPUT
          else
            echo "[NO-GO] PR closed, but not merged!"
            echo "PR_MERGED=false" >> $GITHUB_OUTPUT
          fi

      - id: clone_data_challenges
        name: Clone data-engineering-challenges
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner}}/data-engineering-challenges
          token: ${{ secrets.TOKEN }}
          path: data-engineering-challenges

      - id: merge_cha_pr
        name: Merge data-cha PR by branch name
        working-directory: ./data-engineering-challenges
        if: steps.merge-check.outputs.PR_MERGED == 'true'
        run: |
          BRANCH_NAME=${{ github.head_ref }}-challengify
          if [[ `gh pr view ${BRANCH_NAME} 2>&1` =~ "no pull requests found" ]]
          then
            echo "[NO-GO] data-engineering-challenges branch ${BRANCH_NAME} not found"
            exit 1
          fi
          gh pr merge ${BRANCH_NAME} --body "${BRANCH_NAME} auto merged" --squash --auto --delete-branch
          if [[ `gh pr view ${BRANCH_NAME} 2>&1` =~ "no pull requests found" ]]
          then
            echo "[OK] PR from ${BRANCH_NAME} merged into data-engineering-challenges"
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - id: close_cha_pr
        name: Close data-cha PR if data-sol PR was closed without merging
        working-directory: ./data-engineering-challenges
        if: steps.merge-check.outputs.PR_MERGED == 'false'
        run: |
          BRANCH_NAME=${{ github.head_ref }}-challengify
          if [[ `gh pr view ${BRANCH_NAME} 2>&1` =~ "no pull requests found" ]]
          then
            echo "[NO-GO] data-engineering-challenges branch ${BRANCH_NAME} not found"
            exit 1
          fi
          gh pr close ${BRANCH_NAME} --comment "${BRANCH_NAME} closed in data-engineering-solutions" --delete-branch
          if [[ `gh pr view ${BRANCH_NAME} 2>&1` =~ "no pull requests found" ]]
          then
            echo "[OK] PR from ${BRANCH_NAME} closed, branch deleted"
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
