version: "3.9"
services:
  database:
    image: postgres:14
    restart: always
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=f1db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5433:5432

  streamlit:
    build:
      context: .
    restart: always
    volumes:
      - ./.streamlit:/app/.streamlit/
      - ./f1dashboard:/app/f1dashboard/
    command: ["streamlit", "run", "f1dashboard/basic.py"]
    ports:
      - 8501:8501
    depends_on:
      - database
    stdin_open: true # eq. to -i in docker run (allows breakpoints)
    tty: true # eq. to -t in docker run (allows breakpoints)
